languageCode = "en"
languageName = "English"
weight = 1
title = "Moshe Cezana"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = ""
  description = "UX/UI Designer Portfolio"
  # copyright = ""
  dateFormat = "2 January 2006"

[params.author]
  name = "Moshe Cezana"
  image = ""
  headline = "A UX/UI Designer"
  bio = ""
   links = [
   ]
