[[main]]
name = "Work"
pageRef = "work"
weight = 10

[[main]]
name = "About"
pageRef = "about"
weight = 20

[[main]]
identifier = "linkedin"
pre = "linkedin"
url = "https://www.linkedin.com/in/moshe-cezana/"
weight = 30

[[footer]]
none = "none"
