[[main]]
name = "Works"
pageRef = "works"
identifier = "qtA8K4EIht"
weight = 10

[[main]]
identifier = "linkedin"
pre = "linkedin"
url = "https://www.linkedin.com/in/moshe-cezana/"
weight = 20

[[footer]]
none = "none"
